### ISSUE TITLE
Options to disable certain lints?

### ISSUE THREAD

**Issue by TimD1** [awslabs/linter-rules-for-nextflow#34]
**Description**
It would be great if there were an option for specific lints in the selected ruleset to be disabled.

**Use Case**
For example, issue #23 involves the linter raising an error on double-included modules. For projects where this should be allowed, it would be great to have the option to disable specific lints such as this.

**Proposed Solution**
In addition to the `-rulesetfiles=rulesets/general.xml`, it would be great to have an option such as 
`-excluderules=ModuleIncludedTwiceRule,SecondRuleToExclude`.

**Comment by markjschreiber** [comment]
You may already be able to do this. This repo is essentially a set of CodeNarc rules and there are several ways that you can enable, disable or configure rules used by CodeNarc. For example, https://codenarc.org/codenarc-configuring-rules.html#turning-off-a-rule

If one of these options appeals then we could probably update the run scripts/ or container so that exclusions can be passed to CodeNarc.

Another approach might be to use CodeNarc's option to use comments in code to disable rules. As Nextflow is Groovy and can use Groovy comments, the following line should disable `rule1` and `rule2` for code following the comment. I don't think this would prevent the Nextflow engine from running the file

```
// codenarc-disable rule1, rule2

process MYPROCESS {
   ...
}
